In [3]:
import torch as th

/opt/conda/envs/myenv/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [4]:
a = th.tensor([[1,2,3], [4,5,6], [7,8,9], [10,11, 12]])
queue_len = 2

In [5]:
sliding = a.unfold(0, 2, 1)

In [9]:
sliding

tensor([[[ 1,  4],
         [ 2,  5],
         [ 3,  6]],

        [[ 4,  7],
         [ 5,  8],
         [ 6,  9]],

        [[ 7, 10],
         [ 8, 11],
         [ 9, 12]]])

In [41]:
sliding.size()

torch.Size([3, 3, 2])

In [9]:
sliding[0,2]

tensor([3, 6])

In [45]:
c = th.cat(( float('inf')*th.ones((queue_len-1, 3)), a), dim=0)

In [46]:
c

tensor([[inf, inf, inf],
        [ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [47]:
sliding = c.unfold(0, queue_len, 1)

In [48]:
sliding.size()

torch.Size([4, 3, 2])

In [51]:
sliding[0][0]

tensor([inf, 1.])

In [50]:
sliding[2]

tensor([[4., 7.],
        [5., 8.],
        [6., 9.]])

In [31]:
c.size()

torch.Size([6, 3])

In [32]:
a.size()

torch.Size([4, 3])

In [33]:
sliding.size()

torch.Size([4, 3, 3])

In [52]:
sliding

tensor([[[inf,  1.],
         [inf,  2.],
         [inf,  3.]],

        [[ 1.,  4.],
         [ 2.,  5.],
         [ 3.,  6.]],

        [[ 4.,  7.],
         [ 5.,  8.],
         [ 6.,  9.]],

        [[ 7., 10.],
         [ 8., 11.],
         [ 9., 12.]]])

In [53]:
sliding.size()


torch.Size([4, 3, 2])

In [110]:
d = th.cat((sliding, float('inf')*th.ones((sliding.size()[0], sliding.size()[1], queue_len-1))), 2)

In [111]:
sliding.size()

torch.Size([4, 3, 2])

In [112]:
d

tensor([[[inf,  1., inf],
         [inf,  2., inf],
         [inf,  3., inf]],

        [[ 1.,  4., inf],
         [ 2.,  5., inf],
         [ 3.,  6., inf]],

        [[ 4.,  7., inf],
         [ 5.,  8., inf],
         [ 6.,  9., inf]],

        [[ 7., 10., inf],
         [ 8., 11., inf],
         [ 9., 12., inf]]])

In [82]:
d.size()

torch.Size([4, 3, 3])

In [116]:
d_sliding = d.unfold(2, queue_len-1, 1)

In [117]:
d_sliding.size()

torch.Size([4, 3, 3, 1])

In [126]:
m = th.min(d_sliding, dim=3).values
m

tensor([[[inf,  1., inf],
         [inf,  2., inf],
         [inf,  3., inf]],

        [[ 1.,  4., inf],
         [ 2.,  5., inf],
         [ 3.,  6., inf]],

        [[ 4.,  7., inf],
         [ 5.,  8., inf],
         [ 6.,  9., inf]],

        [[ 7., 10., inf],
         [ 8., 11., inf],
         [ 9., 12., inf]]])

In [127]:
m[:,:,1:].size()

torch.Size([4, 3, 2])

In [121]:
m[:,:,1:]

tensor([[[ 1., inf],
         [ 2., inf],
         [ 3., inf]],

        [[ 4., inf],
         [ 5., inf],
         [ 6., inf]],

        [[ 7., inf],
         [ 8., inf],
         [ 9., inf]],

        [[10., inf],
         [11., inf],
         [12., inf]]])

In [123]:
k = th.min(sliding,m[:,:,1:])

In [124]:
k.size()

torch.Size([4, 3, 2])

In [105]:
a = th.max(k, dim=2)

In [108]:
a.values

tensor([[inf, inf, inf],
        [inf, inf, inf],
        [inf, inf, inf],
        [inf, inf, inf]])

In [109]:
a.values.size()

torch.Size([4, 3])

In [125]:
k

tensor([[[ 1.,  1.],
         [ 2.,  2.],
         [ 3.,  3.]],

        [[ 1.,  4.],
         [ 2.,  5.],
         [ 3.,  6.]],

        [[ 4.,  7.],
         [ 5.,  8.],
         [ 6.,  9.]],

        [[ 7., 10.],
         [ 8., 11.],
         [ 9., 12.]]])

In [128]:
k.size()

torch.Size([4, 3, 2])

In [135]:
l = th.max(k, 2).values

In [136]:
l.size()

torch.Size([4, 3])